# config.yaml
data:
  root_dir: /home/zxd/zxd/Huawei/datasets/ori_diffusion  # 你的数据根目录
  condition_dim: 512      # condition 向量的维度
  linear1_shape: [2048, 64] # 根据你的描述 (d_model, dim_ff)
  linear2_shape: [2048, 64] # 根据你的描述 (dim_ff, d_model)
  
model:
  token_size: 256         # 将参数切分成多大的块 (K) 
  hidden_dim: 512         # RNN 和 Diffusion 的内部特征维度
  
  # Recurrent Model (RNN) 配置
  rnn_type: gru         # 可选: gru, lstm, transformer
  rnn_layers: 2
  
  # Diffusion Model 配置
  diff_channels: 128
  diff_layers: 10
  diff_kernel_size: 3
  timesteps: 1000         # 扩散步数
  beta_start: 0.0001
  beta_end: 0.02

train:
  seed: 42
  batch_size: 64       # 论文中大模型用了8，小模型16 [cite: 626]
  num_epochs: 5000
  lr: 3e-4
  min_lr: 1e-8
  lr_scheduler: cosine_warmup
  weight_decay: 1e-5
  num_workers: 4
  save_dir: ./checkpoints
  perm_emb_dim: 64        # 置换状态(Permutation State)的Embedding维度
  max_seeds: 10          # 预估最大的不同seed数量，用于初始化Embedding层
  eval_freq: 10           # 每个epoch评估一次验证集 